import CoreGraphics
import Foundation

/// The vector marks compiled into the package.
///
/// Every icon Simple Icons ships, generated by `Scripts/generate_marks.py` rather than
/// written by hand. Resolving against these costs no network and cannot fail, which is why
/// the resolver asks them first.
///
/// The JSON is read once, on first use, by whichever thread gets there first. That decode is
/// the catalogue's only cost: a few tens of milliseconds for the whole set, paid by the first
/// lookup rather than at launch.
///
/// Read NOTICE before shipping these marks: CC0 covers the drawing, not the trademark, and a
/// few hundred entries carry other terms, which ``BundledMark/license`` reports.
public enum BundledCatalog {
    /// Every bundled mark, ordered by slug.
    public static let all: [BundledMark] = loaded.marks

    /// The mark for a Simple Icons slug, if one is bundled.
    public static func mark(slug: String) -> BundledMark? {
        loaded.marksBySlug[slug]
    }

    /// Marks whose recorded terms forbid commercial use or derivative works.
    ///
    /// Thirteen marks in the generated catalogue, including `vuedotjs`, `sass`, `cocoapods`
    /// and `letsencrypt`. See ``BundledMarkLicense/isRestrictive`` for why these are grouped
    /// apart from attribution and share alike terms, and NOTICE for the full position.
    public static let restrictivelyLicensed: [BundledMark] = loaded.marks.filter {
        $0.license?.isRestrictive == true
    }

    /// Every mark except those whose terms forbid commercial use or derivative works.
    public static let permissivelyLicensed: [BundledMark] = loaded.marks.filter {
        $0.license?.isRestrictive != true
    }

    /// The Simple Icons release the marks were generated from.
    public static var sourceVersion: String { loaded.sourceVersion }

    private static let loaded = Catalog.load()

    private struct Catalog: Sendable {
        let marks: [BundledMark]
        let marksBySlug: [String: BundledMark]
        let sourceVersion: String

        static let empty = Catalog(marks: [], marksBySlug: [:], sourceVersion: "")

        static func load() -> Catalog {
            guard let url = Bundle.module.url(forResource: "BrandMarks", withExtension: "json"),
                  let data = try? Data(contentsOf: url),
                  let file = try? JSONDecoder().decode(File.self, from: data)
            else { return .empty }

            var marks: [BundledMark] = []
            var marksBySlug: [String: BundledMark] = [:]
            marks.reserveCapacity(file.marks.count)

            for entry in file.marks {
                guard let mark = entry.mark else { continue }
                marks.append(mark)
                marksBySlug[mark.slug] = mark
            }

            return Catalog(
                marks: marks,
                marksBySlug: marksBySlug,
                sourceVersion: file.sourceVersion
            )
        }
    }

    private struct File: Decodable {
        let sourceVersion: String
        let marks: [Entry]
    }

    private struct Entry: Decodable {
        let slug: String
        let title: String
        let path: String
        let viewBox: [Double]
        let tint: String
        let license: License?

        var mark: BundledMark? {
            guard !slug.isEmpty, !path.isEmpty, viewBox.count == 4,
                  viewBox[2] > 0, viewBox[3] > 0,
                  let tint = BrandColor(hex: tint)
            else { return nil }

            return BundledMark(
                slug: slug,
                title: title,
                pathData: path,
                viewBox: CGRect(x: viewBox[0], y: viewBox[1], width: viewBox[2], height: viewBox[3]),
                tint: tint,
                license: license.map { $0.value }
            )
        }
    }

    private struct License: Decodable {
        let type: String
        let url: String?

        var value: BundledMarkLicense {
            BundledMarkLicense(type: type, url: url.flatMap(URL.init(string:)))
        }
    }
}
